name: Test
on:
  workflow_dispatch: {}
jobs:
  deploy_maven_test:
    runs-on:
      - test
    name: Deploy - Maven
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: maven